import { ShoperStock } from "../../src/models/shoper-stock";

export let shoperStockMockup: ShoperStock = {
  stock_id: "48",
  extended: "0",
  price: "549.00",
  price_buying: "0.00",
  price_type: "1",
  stock: "3",
  package: "0",
  warn_level: "1",
  sold: "0",
  weight: "30",
  weight_type: "1",
  active: "1",
  default: "1",
  product_id: "48",
  availability_id: null,
  delivery_id: "1",
  gfx_id: null,
  code: "SADIW50801A",
  ean: "",
  comp_weight: "30",
  comp_price: "549.00",
  comp_promo_price: "549.00",
  price_wholesale: "549.00",
  comp_price_wholesale: "549.00",
  comp_promo_price_wholesale: "549.00",
  price_special: "549.00",
  comp_price_special: "549.00",
  comp_promo_price_special: "549.00",
  price_type_wholesale: "0",
  price_type_special: "0",
  calculation_unit_id: null,
  calculation_unit_ratio: "0",
  options: []
};
