import { ShoperStock } from "./shoper-stock";

export type ShoperProduct = {
  product_id: string;
  producer_id: string;
  group_id: string;
  tax_id: string;
  add_date: string;
  edit_date: string;
  other_price: string;
  pkwiu: string;
  unit_id: string;
  in_loyalty: string;
  loyalty_score: string;
  loyalty_price: string;
  bestseller: string;
  newproduct: string;
  dimension_w: string;
  dimension_h: string;
  dimension_l: string;
  vol_weight: string;
  currency_id: string;
  gauge_id: string;
  unit_price_calculation: string;
  type: string;
  category_id: string;
  categories: number[];
  promo_price: string;
  code: string;
  ean: string;
  stock: ShoperStock;
  translations: any;
  options: number[];
  attributes: number[];
  related: number[];
  main_image: any;
  is_product_of_day: boolean;
  feeds_excludes: number[];
};
